<?php

namespace ContainerUK30zVG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityHelperControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EntityHelperController' shared autowired service.
     *
     * @return \App\Controller\EntityHelperController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/EntityHelperController.php';

        return $container->services['App\\Controller\\EntityHelperController'] = new \App\Controller\EntityHelperController();
    }
}
