<?php

namespace ContainerUK30zVG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderViewControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RenderViewController' shared autowired service.
     *
     * @return \App\Controller\RenderViewController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/RenderViewController.php';

        return $container->services['App\\Controller\\RenderViewController'] = new \App\Controller\RenderViewController(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
