<?php

namespace ContainerY3w6iv4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComunidadControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ComunidadController' shared autowired service.
     *
     * @return \App\Controller\ComunidadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ComunidadController.php';

        return $container->services['App\\Controller\\ComunidadController'] = new \App\Controller\ComunidadController(($container->privates['App\\Repository\\ComunidadRepository'] ?? $container->load('getComunidadRepositoryService')));
    }
}
