<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUK30zVG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUK30zVG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUK30zVG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUK30zVG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUK30zVG\App_KernelDevDebugContainer([
    'container.build_hash' => 'UK30zVG',
    'container.build_id' => 'f4c875af',
    'container.build_time' => 1626425535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUK30zVG');
