<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'add_comunidad' => [[], ['_controller' => 'App\\Controller\\ComunidadController::insert'], [], [['text', '/comunidad']], [], []],
    'update_comunidad' => [['idcomunidad'], ['_controller' => 'App\\Controller\\ComunidadController::update'], [], [['variable', '/', '[^/]++', 'idcomunidad', true], ['text', '/comunidad']], [], []],
    'delete_comunidad' => [['idcomunidad'], ['_controller' => 'App\\Controller\\ComunidadController::delete'], [], [['variable', '/', '[^/]++', 'idcomunidad', true], ['text', '/comunidad']], [], []],
    'get_one_comunidad' => [['idcomunidad'], ['_controller' => 'App\\Controller\\ComunidadController::get'], [], [['variable', '/', '[^/]++', 'idcomunidad', true], ['text', '/comunidad']], [], []],
    'get_all_comunidades' => [[], ['_controller' => 'App\\Controller\\ComunidadController::getAll'], [], [['text', '/comunidades']], [], []],
    'getview_post' => [[], ['_controller' => 'App\\Controller\\RenderViewController::renderView'], [], [['text', '/getview']], [], []],
    'checklogin' => [[], ['_controller' => 'App\\Controller\\SecurityController::checkLogin'], [], [['text', '/checklogin']], [], []],
    'get_all_usuarios' => [[], ['_controller' => 'App\\Controller\\UsuarioController::getAll'], [], [['text', '/usuarios']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/api/v1/']], [], []],
];
