<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \App\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
  'comunidades' => NULL,
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
  'comunidades' => NULL,
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        unset($this->comunidades);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);

    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (\array_key_exists($name, self::$lazyPropertiesNames)) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'cif', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'localidad', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idlocalidad', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idprovincia', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'codpostal', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'emailcontacto', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idrol', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'usercreate', 'comunidades'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'cif', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'localidad', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idlocalidad', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idprovincia', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'codpostal', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'telefono', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'emailcontacto', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'idrol', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'created', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'updated', '' . "\0" . 'App\\Entity\\Usuarios' . "\0" . 'usercreate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->comunidades);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif(string $cif): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion(?string $direccion): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad(?string $localidad): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdlocalidad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlocalidad', []);

        return parent::getIdlocalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdlocalidad(?int $idlocalidad): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdlocalidad', [$idlocalidad]);

        return parent::setIdlocalidad($idlocalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdprovincia(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprovincia', []);

        return parent::getIdprovincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdprovincia(?int $idprovincia): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdprovincia', [$idprovincia]);

        return parent::setIdprovincia($idprovincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodpostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodpostal', []);

        return parent::getCodpostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodpostal(?string $codpostal): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodpostal', [$codpostal]);

        return parent::setCodpostal($codpostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono(?string $telefono): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailcontacto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailcontacto', []);

        return parent::getEmailcontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailcontacto(string $emailcontacto): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailcontacto', [$emailcontacto]);

        return parent::setEmailcontacto($emailcontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrol(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrol', []);

        return parent::getIdrol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrol(int $idrol): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrol', [$idrol]);

        return parent::setIdrol($idrol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt(string $salt): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken(?string $token): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(string $estado): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTimeInterface $created = NULL): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated(\DateTimeInterface $updated = NULL): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsercreate(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsercreate', []);

        return parent::getUsercreate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsercreate(?int $idusuario): \App\Entity\Usuarios
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsercreate', [$idusuario]);

        return parent::setUsercreate($idusuario);
    }

}
